### ISSUE TITLE
Do you have a pretrained model?

### ISSUE THREAD

**Issue by c1a1o1** [LonglongaaaGo/EXE-GAN#1]
Do you have a pretrained model?

**Comment by c1a1o1** [comment]
Great work！

**Comment by LonglongaaaGo** [comment]
> Do you have a pretrained model?

Thank you for your attention. We will release our codes after accepted.

**Comment by LonglongaaaGo** [comment]
> Great work！

Thank you so much for your attention. We have released our codes.
