### ISSUE TITLE
Missing model class

### ISSUE THREAD

**Issue by rosauravidal** [LonglongaaaGo/EXE-GAN#10]
When trying to run the guided_recovery, the following is called inside test.py:

```
from models.exe_gan_model import EXE_GAN
from models.stylegan2_co_mod_gan import co_mod_GAN
```

Where can I get these files?

**Comment by LonglongaaaGo** [comment]
Hi @rosauravidal 

Thanks for your attention.
I have revised the code.
Could you check it again?
Let me know if it can solve the problem.
Thanks!

**Comment by LonglongaaaGo** [comment]
We can reopen it if we have any issues.
